### PR TITLE
Improve german translation

### PR DESCRIPTION
**Pull request by ehda93**

### CODE REVIEW

**Review by xEdziu — APPROVED** [review]
Thank you for improving the german version of translation!

**Comment by ehda93** [comment]
Thanks for approving - Please don't merge before 1st of October

**Comment by xEdziu** [comment]
Yea, I don't merge any PR's before 1st October

**Review by xEdziu — CHANGES_REQUESTED** [review]
There are conflits with actually existing language file, would you mind resolving it?

**Comment by xEdziu** [comment]
Hi @ehda93, as this is another German language improvement, if you will not resolve conflicts today, I will have to close this PR :(

**Comment by ehda93** [comment]
Hi @xEdziu, i will try to resolve them today.

**Review by xEdziu — APPROVED** [review]

**Comment by xEdziu** [comment]
Thank you for your contribution!

**Comment by ehda93** [comment]
Resolved conflicts. IMHO a lot of conflicts were just about formal/informal version

**Pull request merged**
