### PR TITLE
Improved german once more and rephrased some english entries

### PR DESCRIPTION
**Pull request by justDabuK**
**Changes**
- there were some typos in the german translation
- I rephrased some german entries
- I also rephrased some english entires
- I removed some inconsistent punctuations

### CODE REVIEW

**Review by xEdziu — CHANGES_REQUESTED** [review]
Now there are some special german characters that are not compatible with Unicode, please improve that! :D

**Review by xEdziu — APPROVED** [review]

**Review by xEdziu — CHANGES_REQUESTED** [review]
English is okay, but German needs to be compatibile with Unicode characters, thank you for your time and effort!

**Comment by justDabuK** [comment]
Oh good point with the unicode characters 😅 
I'll improve that 👍🏽

**Comment by xEdziu** [comment]
> Oh good point with the unicode characters 😅 I'll improve that 👍🏽

Thank you a lot! <3

**Review by xEdziu — APPROVED** [review]

**Comment by justDabuK** [comment]
Now the "Files changed" tab looks way better aswell 👌🏽 

6dfc0d768fb19cfe4d4981a3b71b5813b6495521 ✅

**Comment by xEdziu** [comment]
Now everything is good :D, thank you a lot!

**Review by xEdziu — APPROVED** [review]

**Comment by justDabuK** [comment]
You're welcome ☺️

**Comment by xEdziu** [comment]
Hi @justDabuK, there are some conflicts in German language, would you mind resolving them?

**Review by xEdziu — CHANGES_REQUESTED** [review]
Conflicts with actually exisiting German language :(

**Comment by justDabuK** [comment]
Of course 👍🏽

**Comment by justDabuK** [comment]
strange I didn't want to close this one, I'll reopen it

**Comment by justDabuK** [comment]
I fixed the conflicts 👍🏽

**Review by xEdziu — APPROVED** [review]

**Pull request merged**
