### PR TITLE
Create language_it-it.properties

### PR DESCRIPTION
**Pull request by TheZal**
Created the language it-it properties file

### CODE REVIEW

**Review by xEdziu — APPROVED** [review]
Thank you for your contribution!

**Comment by TheZal** [comment]
:)

**Comment by xEdziu** [comment]
Hi @TheZal, there are some conflicts, would you mind resolving them?

**Review by xEdziu — CHANGES_REQUESTED** [review]
Conflicts with actually existing italian translation :(

**Comment by xEdziu** [comment]
Hi, as it is another translation from Italian, if you will not resolve conflicts today, I will have to close this PR :(

**Comment by xEdziu** [comment]
@TheZal Please acknowledge yourself with that, I don't want to be mean during hacktoberfest :(

**Comment by TheZal** [comment]
Gonna work on that asap but when I checked there wasn't an Italian translation!

**Comment by TheZal** [comment]
Is that ok?

**Review by xEdziu — APPROVED** [review]

**Comment by xEdziu** [comment]
It will do the job :)

**Comment by TheZal** [comment]
Thanks!

**Pull request merged**
