### PR TITLE
Update Hindi language_hi-in.properties

### PR DESCRIPTION
**Pull request by maharshi-sinha**
Fixing some grammatical mistakes and improving the Hindi language.

### CODE REVIEW

**Review by xEdziu — APPROVED** [review]

**Comment by xEdziu** [comment]
Thank you for your contribution!

**Comment by Tyagiquamar** [comment]
Hello sir, I want to contribute to this project.
As in India hindi is used differently, Iwant to create two hindi translation--
1.In full Hindi with formal wording(Most people wont understand) as you current file.
2. In casual language which most people use (they use a lot of english world instead of complex hindi word (they don't even know them) to make it able to be understandale by all.

**Comment by xEdziu** [comment]
> Hello sir, I want to contribute to this project. As in India hindi is used differently, Iwant to create two hindi translation-- 1.In full Hindi with formal wording(Most people wont understand) as you current file. 2. In casual language which most people use (they use a lot of english world instead of complex hindi word (they don't even know them) to make it able to be understandale by all.

Okay, I believe it is doable somehow, what should we call this new file?

**Review by xEdziu — APPROVED** [review]

**Comment by Tyagiquamar** [comment]
Simple readme
Or simple instructions

**Pull request merged**
