### PR TITLE
Create language_in-id.properties

### PR DESCRIPTION
**Pull request by ifs20004-itdel**
Create a new property in Indonesian language

### CODE REVIEW

**Review by xEdziu — APPROVED** [review]

**Comment by xEdziu** [comment]
Thank you for your translation!

**Review by xEdziu — CHANGES_REQUESTED** [review]
Conflict with exisitng in-id translation file :(

**Comment by xEdziu** [comment]
Hi, as it is another translation from Indonesian, if you will not resolve conflicts today, I will have to close this PR :(

**Comment by ifs20004-itdel** [comment]
Hi, my apology for the late reply
It's ok if you close the PR, as I already checked the file in-id.properties
before me, and it is nearly the same with my translation. So it's ok
Thank you

__
Samuel Sibuea

Pada tanggal Min, 2 Okt 2022 pukul 19.59 Adrian Goral <
***@***.***> menulis:

**Comment by xEdziu** [comment]
Okay, thank you for your answer!

**Pull request closed without merging**
