### PR TITLE
Added gujarati-english translation

### PR DESCRIPTION
**Pull request by varunnitian**

### CODE REVIEW

**Comment by xEdziu** [comment]
@varunnitian what locale code that this language has?

**Comment by xEdziu** [comment]
@varunnitian please check the locale here and commit once more https://wiki.freepascal.org/Language_Codes :D

**Review by xEdziu — CHANGES_REQUESTED** [review]
I don't really know what this locale is, so if you could maybe describe it a little more, I would be gratefull

**Comment by varunnitian** [comment]
@xEdziu the translation has been done in Gujarati language and this language is one of the languages spoken in the Gujarat state of India.I have changed the locale code from guj to gu as mentioned in https://wiki.freepascal.org/Language_Codes. Thanks :)

**Review by xEdziu — APPROVED** [review]

**Review by xEdziu — APPROVED** [review]

**Review by xEdziu — APPROVED** [review]

**Pull request merged**
