### PR TITLE
Update language_ro-ro.properties

### PR DESCRIPTION
**Pull request by zghp**
Make spelling/grammar adjustments and replace strings with a more native-like phrasing

### CODE REVIEW

**Review by xEdziu — APPROVED** [review]
Thank you very much for your contribution!

**Comment by zghp** [comment]
Hi, I can.t see the pull request on my hacktoberfest page, i wonder if it.s because you added the labels before the 1st of Oct? It.s my 1st year participating so still trying to understand how this all works😬

Do you have any idea? thank you so much 🙆🏻‍♀️

**Comment by xEdziu** [comment]
> Hi, I can.t see the pull request on my hacktoberfest page, i wonder if it.s because you added the labels before the 1st of Oct? It.s my 1st year participating so still trying to understand how this all works😬
> 
> Do you have any idea? thank you so much 🙆🏻‍♀️

HI, it is my first year participating too and I have no idea why you can't see it :( I will merge all PRs in a few days so maybe it will be helpfull

**Comment by zghp** [comment]
hmm, i see.. if you have a few mins to spare then can you please remove and after add the labels back?🙏🏻

**Comment by xEdziu** [comment]
i can try

**Comment by zghp** [comment]
Me again, sorry to bother. So looks like anything submitted before the 1st of Oct is not counted at all so one last request, would it be fine if you delete this merge request and I create a new one? Hope it doesn't clutter the project too much

**Comment by xEdziu** [comment]
> Me again, sorry to bother. So looks like anything submitted before the 1st of Oct is not counted at all so one last request, would it be fine if you delete this merge request and I create a new one? Hope it doesn't clutter the project too much

Okay, no problem we can do it like that :D

**Pull request closed without merging**
