### PR TITLE
Hindi translations added, corrected a word in english, addresses desktop launch icon issue

### PR DESCRIPTION
**Pull request by anjannair**
This PR does 2 things - 

- Added Hindi translation and corrected a word in English #50 
- Solves issue #66 with a shell script

Linux users can just run the following command -
```bash
wget -qO- https://link-to-script | bash 
```
Test it through my fork -
```bash
wget -qO- https://raw.githubusercontent.com/anjannair/KeepMyPassword-Desktop/main/linux-install.sh | bash
```

And this would install the application

### CODE REVIEW

**Review by xEdziu — APPROVED** [review]

**Review by xEdziu — APPROVED** [review]
Wooow! That's awesome! Thank you a lot! I really appreciate the effort!

**Comment by xEdziu** [comment]
@all-contributors please add @anjannair for code and translation

**Comment by anjannair** [comment]
@xEdziu Do modify the wiki so that folks using Linux can use the script!

**Comment by xEdziu** [comment]
@anjannair I will as soon as when I figure out why does linux version do not launch (probably maven issue, I will figure it out!)

You're the real hero here! <3

**Comment by anjannair** [comment]
@xEdziu could you tell me how I can build the project for developing it? Like I'm familiar with Java but pretty new to Maven

I'll try helping you fix the Linux issue!

**Comment by xEdziu** [comment]
Make sure that you have maven installed and can access it globally (set up an env variable for maven).

Next, head up to the project itself, open it, and type `mvn clean package`, and that should be it!

**Comment by anjannair** [comment]
@xEdziu I did what you said and the generated file `KeepMyPassword-Desktop-3.1.0-jar-with-dependencies.jar` works perfectly for Debian based systems

image

**Comment by xEdziu** [comment]
@anjannair great! That states that this is my os problem, to be sure, I did something wrong there.

Is there a possibility, to contact you via discord?

**Comment by anjannair** [comment]
> @anjannair great! That states that this is my os problem, to be sure, I did something wrong there.
> 
> Is there a possibility, to contact you via discord? 

Check your mail!

**Pull request merged**
